/* Generated by cbindgen - do not edit */

#ifndef MORDRED_H
#define MORDRED_H

/* Warning: this file is autogenously generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a descriptor calculator.
 */
typedef struct MordredCalculator MordredCalculator;

/**
 * Opaque handle to a parsed molecule.
 */
typedef struct MordredMolecule MordredMolecule;

/**
 * Opaque handle to a calculation result set.
 */
typedef struct MordredResult MordredResult;

/**
 * Create a new calculator containing every built-in descriptor.
 *
 * The returned pointer must be freed with `mordred_calculator_free`.
 */
struct MordredCalculator *mordred_calculator_new(void);

/**
 * Free a calculator previously created by `mordred_calculator_new`.
 *
 * Passing a null pointer is a no-op.
 *
 * # Safety
 *
 * `calc` must be a pointer returned by `mordred_calculator_new` and must not
 * have been freed already.
 */
void mordred_calculator_free(struct MordredCalculator *calc);

/**
 * Parse a SMILES string into a molecule handle.
 *
 * On success a non-null pointer is returned and `*error_out` is left
 * unchanged.  On failure null is returned and, if `error_out` is non-null,
 * `*error_out` is set to a heap-allocated error string that must be freed
 * with `mordred_string_free`.
 *
 * # Safety
 *
 * `smiles` must be a valid null-terminated C string.
 */
struct MordredMolecule *mordred_molecule_from_smiles(const char *smiles, char **error_out);

/**
 * Free a molecule previously created by `mordred_molecule_from_smiles`.
 *
 * Passing a null pointer is a no-op.
 *
 * # Safety
 *
 * `mol` must be a pointer returned by `mordred_molecule_from_smiles` and must
 * not have been freed already.
 */
void mordred_molecule_free(struct MordredMolecule *mol);

/**
 * Calculate all descriptors for a molecule.
 *
 * Returns a result handle that must be freed with `mordred_result_free`.
 * Returns null if either `calc` or `mol` is null.
 *
 * # Safety
 *
 * Both `calc` and `mol` must be valid, non-freed pointers obtained from the
 * corresponding constructor functions.
 */
struct MordredResult *mordred_calculate(const struct MordredCalculator *calc,
                                        const struct MordredMolecule *mol);

/**
 * Free a result set previously returned by `mordred_calculate`.
 *
 * Passing a null pointer is a no-op.
 *
 * # Safety
 *
 * `result` must be a pointer returned by `mordred_calculate` and must not
 * have been freed already.
 */
void mordred_result_free(struct MordredResult *result);

/**
 * Return the number of entries in the result set.
 *
 * Returns 0 if `result` is null.
 *
 * # Safety
 *
 * `result` must be a valid, non-freed pointer returned by `mordred_calculate`,
 * or null.
 */
uintptr_t mordred_result_len(const struct MordredResult *result);

/**
 * Return the descriptor name for the entry at `index`.
 *
 * The returned pointer is valid until `mordred_result_free` is called.
 * Returns null if `result` is null or `index` is out of bounds.
 *
 * # Safety
 *
 * `result` must be a valid, non-freed pointer returned by `mordred_calculate`,
 * or null.
 */
const char *mordred_result_name(const struct MordredResult *result, uintptr_t index);

/**
 * Return whether the calculation for the entry at `index` succeeded.
 *
 * Returns `false` if `result` is null or `index` is out of bounds.
 *
 * # Safety
 *
 * `result` must be a valid, non-freed pointer returned by `mordred_calculate`,
 * or null.
 */
bool mordred_result_is_ok(const struct MordredResult *result, uintptr_t index);

/**
 * Return the descriptor value for the entry at `index`.
 *
 * Returns `NaN` if the calculation failed, `result` is null, or `index` is
 * out of bounds.
 *
 * # Safety
 *
 * `result` must be a valid, non-freed pointer returned by `mordred_calculate`,
 * or null.
 */
double mordred_result_value(const struct MordredResult *result, uintptr_t index);

/**
 * Return the number of descriptors in the calculator.
 *
 * Returns 0 if `calc` is null.
 *
 * # Safety
 *
 * `calc` must be a valid, non-freed pointer returned by
 * `mordred_calculator_new`, or null.
 */
uintptr_t mordred_calculator_descriptor_count(const struct MordredCalculator *calc);

/**
 * Return the name of the descriptor at `index`.
 *
 * The returned pointer is valid until `mordred_calculator_free` is called.
 * Returns null if `calc` is null or `index` is out of bounds.
 *
 * # Safety
 *
 * `calc` must be a valid, non-freed pointer returned by
 * `mordred_calculator_new`, or null.
 */
const char *mordred_calculator_descriptor_name(const struct MordredCalculator *calc,
                                               uintptr_t index);

/**
 * Free a string previously allocated by mordred (e.g. an error message set by
 * `mordred_molecule_from_smiles`).
 *
 * Passing a null pointer is a no-op.
 *
 * # Safety
 *
 * `s` must be a pointer previously returned via an error-out parameter, or
 * null.
 */
void mordred_string_free(char *s);

#endif  /* MORDRED_H */
